import type { ScanResult, OutputFormat } from './types.js';

function bar(earned: number, max: number, width = 10): string {
  const filled = max > 0 ? Math.round((earned / max) * width) : 0;
  return '█'.repeat(filled) + '░'.repeat(width - filled);
}

function pad(str: string, len: number): string {
  return str.length >= len ? str.slice(0, len) : str + ' '.repeat(len - str.length);
}

function rpad(str: string, len: number): string {
  return str.length >= len ? str : ' '.repeat(len - str.length) + str;
}

// ── Console ───────────────────────────────────────────────────────
function formatConsole(r: ScanResult): string {
  const W = 58;
  const line = (s: string) => `║  ${s}${' '.repeat(Math.max(0, W - 2 - s.length))}║`;
  const top = `╔${'═'.repeat(W)}╗`;
  const bot = `╚${'═'.repeat(W)}╝`;
  const div = `╠${'═'.repeat(W)}╣`;
  const empty = `║${' '.repeat(W)}║`;

  const lines = [top];
  lines.push(line('PRISM D1: Velocity Assessment'));
  lines.push(line(`Repository: ${r.repoName}`));
  lines.push(line(`Date: ${r.scanDate}`));
  lines.push(div, empty);

  const sBar = bar(r.totalScore, r.maxScore, 20);
  lines.push(line(`PRISM Level: ${r.prismLevel.level}  ${sBar} (${r.totalScore}/${r.maxScore})`));
  lines.push(line(r.prismLevel.description));
  lines.push(empty);

  for (const c of r.categories) {
    lines.push(line(`${pad(c.category, 20)}${bar(c.earnedPoints, c.maxPoints)}  ${rpad(`${c.earnedPoints}/${c.maxPoints}`, 6)}`));
  }
  lines.push(empty);

  if (r.strengths.length) {
    lines.push(line('TOP STRENGTHS'));
    r.strengths.forEach((s, i) => lines.push(line(`  ${i + 1}. ${s}`)));
    lines.push(empty);
  }
  if (r.gaps.length) {
    lines.push(line('TOP GAPS'));
    r.gaps.forEach((g, i) => lines.push(line(`  ${i + 1}. ${g}`)));
    lines.push(empty);
  }
  if (r.recommendations.length) {
    lines.push(line('RECOMMENDED ACTIONS'));
    r.recommendations.forEach(rec => lines.push(line(`  → ${rec}`)));
    lines.push(empty);
  }
  lines.push(bot);
  return lines.join('\n');
}

// ── JSON ──────────────────────────────────────────────────────────
function formatJSON(r: ScanResult): string {
  return JSON.stringify(r, null, 2);
}

// ── Markdown ──────────────────────────────────────────────────────
function formatMarkdown(r: ScanResult): string {
  const lines = [
    '# PRISM D1: Velocity Assessment', '',
    `| Field | Value |`, `|-------|-------|`,
    `| **Repository** | \`${r.repoName}\` |`,
    `| **Date** | ${r.scanDate} |`,
    `| **PRISM Level** | **${r.prismLevel.level}** (${r.prismLevel.label}) |`,
    `| **Score** | **${r.totalScore}/${r.maxScore}** |`, '',
    '## Category Breakdown', '',
    '| Category | Score | Bar |', '|----------|-------|-----|',
  ];
  for (const c of r.categories) {
    lines.push(`| ${c.category} | ${c.earnedPoints}/${c.maxPoints} | \`${bar(c.earnedPoints, c.maxPoints)}\` |`);
  }
  lines.push('', '## Evidence Detail', '');
  for (const c of r.categories) {
    lines.push(`### ${c.category} (${c.earnedPoints}/${c.maxPoints})`, '');
    for (const e of c.evidence) lines.push(`- ${e.found ? '✅' : '❌'} **${e.signal}** (${e.points} pts) — ${e.detail}`);
    lines.push('');
  }
  if (r.strengths.length) { lines.push('## Top Strengths', ''); r.strengths.forEach((s, i) => lines.push(`${i + 1}. ${s}`)); lines.push(''); }
  if (r.gaps.length) { lines.push('## Top Gaps', ''); r.gaps.forEach((g, i) => lines.push(`${i + 1}. ${g}`)); lines.push(''); }
  if (r.recommendations.length) { lines.push('## Recommended Actions', ''); r.recommendations.forEach(rec => lines.push(`- ${rec}`)); lines.push(''); }
  lines.push('---', '*Generated by PRISM D1 Velocity Scanner*');
  return lines.join('\n');
}

// ── Dispatcher ────────────────────────────────────────────────────
export function formatReport(result: ScanResult, format: OutputFormat): string {
  switch (format) {
    case 'json': return formatJSON(result);
    case 'markdown': return formatMarkdown(result);
    default: return formatConsole(result);
  }
}
